sfSimpleCMSPage:
  tableName:        sf_simple_cms_page
  options:
      treeImpl: NestedSet
  columns:
    id:
      type: integer
      length: 4
      primary: true
      autoincrement: true
    created_at: 
      type: timestamp
    updated_at: 
      type: timestamp  
    slug:
      type: string
      length: 255
      notnull: true
    topic_id:
      type: integer
    template:
      type: string
      length: 100
    is_published:
      type: boolean
      length: null
    locked_by:
      type: integer
      length: 4
      notnull: false
  relation:
    lockedPages:
      class: sfGuardUser
      foreign: id
      local: locked_by

sfSimpleCMSSlot:
  tableName:      sf_simple_cms_slot
  columns:
    page_id:
      type:   integer
      length:   4
      foreignClass: sfSimpleCMSPage
      foreignReference: id
      localName: sfSimpleCMSSlots
      foreignName: page
      notnull:  true
      cascadeDelete: true
      primary: true
    culture:
      type: string
      length: 7
      notnull: true
      primary: true
    name:
      type: string
      length: 100
      notnull: true
      primary: true
    type:
      type: string
      length: 100
      notnull: true
      default: Text
    value:
      type: string
      length: 4000
    created_at: 
      type: timestamp
    updated_at: 
      type: timestamp
