---
sfSimpleCMSPage:
  tableName: sf_simple_cms_page
  actAs: [Timestampable, Sluggable, NestedSet]
  columns:
    id:
      type: integer(4)
      primary: true
      autoincrement: true
    topic_id:
      type: integer
    template:
      type: string(100)
    is_published:
      type: boolean
      length: null
    locked_by:
      type: integer(4)
      notnull: false
  relations:
    LockedBy:
      class: sfGuardUser
      local: locked_by
      foreign: id
      foreignAlias: LockedPages

sfSimpleCMSSlot:
  tableName: sf_simple_cms_slot
  actAs: [Timestampable]
  columns:
    page_id:
      type:   integer(4)
      notnull:  true
      primary: true
    culture:
      type: string(7)
      notnull: true
      primary: true
    name:
      type: string(100)
      notnull: true
      primary: true
    type:
      type: string(100)
      notnull: true
      default: Text
    value:
      type: string(4000)
  relations:
    sfSimpleCMSPage:
      local: page_id
      foreign: id
      onDelete: CASCADE
      foreignAlias: sfSimpleCMSSlots